package pl.wk.s02w040RuntimeVsCheckedExeptions;

public class App {
    public static void main(String[] args) {

        //java.lang.ArithmeticException: / by zero
//        int value = 7;
//        value = value/0;


        //java.lang.NullPointerException
//        String text = null;
//        System.out.println(text.length());

        //java.lang.ArrayIndexOutOfBoundsException: 3
//        String[] texts = {"one", "teo", "three"};
//        try {
//            System.out.println(texts[3]);
//        } catch (Exception e) {
//            System.out.println(e.toString());
//        }

//        String[] texts = {"one", "teo", "three"};
//        try {
//            System.out.println(texts[3]);
//        } catch (RuntimeException e) {
//            System.out.println(e.toString());
//        }
//
//        String[] texts = {"one", "teo", "three"};
//        try {
//            System.out.println(texts[3]);
//        } catch (ArrayIndexOutOfBoundsException e) {
//            System.out.println(e.toString());
//        }
    }
}
